name: Cypress Tests

on:
  push:
    branches-ignore:
      - "renovate/**"

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.12.0-chrome-123.0.6312.86-1-ff-124.0.2-edge-123.0.2420.65-1
      options: --user 1001
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # Run 3 jobs in parallel on different browser
        browser:
          - chrome
          - electron
          - edge
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
      # report machine parameters
      - run: yarn cypress info
      - run: node --version
      - run: node -p 'os.cpus()'
      - run: yarn types
      - run: yarn lint
      - run: yarn test:unit:ci
      - run: yarn build:ci

      - name: Unblock Cypress
        run: |
          echo ### Download Free Cypress ###
          CYPRESS_DOWNLOAD_MIRROR=https://cy-cdn.currents.dev npx cypress install --force
          echo ### Verify Cypress ###
          npx cypress verify
          echo ### Cypress Cache ###
          npx cypress cache list
          npx cypress cache path
      # Run Cypress tests And send Data to Sorry-Cypress Step
      - name: Run Cypress Tests And send Data to Sorry-Cypress
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          install: false
          build: npm run cy:info
          wait-on-timeout: 180
          browser: ${{ matrix.browser }}
          config-file: cypress.config.js
          command: |
            npx cypress-cloud run --parallel --browser ${{ matrix.browser }} --key somekey --ci-build-id Run#${{ github.run_id }}-${{ matrix.browser }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: "cypress:server:args"
